name: Contributors List
on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 3 */2 * *"

jobs:
  contributors:
    runs-on: ubuntu-latest
    name: Update contributors list
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Contributors
        uses: wow-actions/contributors-list@v1
        with:
          svgPath: .github/assets/CONTRIBUTORS.svg
          round: true
          noCommit: true
      
      - name: Commit & PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(): update contributors-list"
          commit-message: 'chore(): update contributors-list'
          add-paths: .github/assets/CONTRIBUTORS.svg
          branch: ci-update-contributors-list
          base: ${{ github.event.repository.default_branch }}
          delete-branch: true
          body: |
            Automated update to `.github/assets/CONTRIBUTORS.svg`

