name: Contributors List
on:
  schedule:
    - cron: "0 3 */2 * *"

jobs:
  contributors:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
       - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Contributors
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: .github/assets/CONTRIBUTORS.svg
          round: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(): update contributors-list'
          title: Update Contributors
          body: Credit new contributors
          branch: update-contributors
